version: "3.6"

services:
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: consorcio
    container_name: mysql
    image: mysql:8.4
    volumes:
      - mysql_volume:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306

  #grpc:

volumes:
  mysql_volume: