version: "3.6"

services:
  mysql:
    enviroment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ejemplo
    container-name: mysql
    image: mysql:8.4
    volumes:
      - mysql_volume:/var/lib/mysql
    ports:
      - 3306:3306

  #grpc:

volumes:
  mysql_volume: