version: "3.9"

services:
  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: consorcio
    ports:
      - "3306:3306"    
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure  
    
  suscripciones_noticias:
    image: suscripciones_noticias:latest
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "50051:50051"  
    

networks:
  app-network:
    driver: overlay
