# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: suscripciones_noticias.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'suscripciones_noticias.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1csuscripciones_noticias.proto\x12\rsuscripciones\"A\n\x0b\x43lienteArea\x12\x12\n\ncliente_id\x18\x01 \x01(\x05\x12\x0c\n\x04\x61rea\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"+\n\tRespuesta\x12\x0f\n\x07mensaje\x18\x01 \x01(\t\x12\r\n\x05\x65xito\x18\x02 \x01(\x08\"\x16\n\x04\x41rea\x12\x0e\n\x06nombre\x18\x01 \x01(\t\"!\n\rListaClientes\x12\x10\n\x08\x63lientes\x18\x01 \x03(\t\";\n\x07Noticia\x12\x0e\n\x06titulo\x18\x01 \x01(\t\x12\x11\n\tcontenido\x18\x02 \x01(\t\x12\r\n\x05\x66\x65\x63ha\x18\x03 \x01(\t\"9\n\rListaNoticias\x12(\n\x08noticias\x18\x01 \x03(\x0b\x32\x16.suscripciones.Noticia2\xc6\x02\n\x15SuscripcionesNoticias\x12I\n\x11SubscribirCliente\x12\x1a.suscripciones.ClienteArea\x1a\x18.suscripciones.Respuesta\x12I\n\x11\x42orrarSuscripcion\x12\x1a.suscripciones.ClienteArea\x1a\x18.suscripciones.Respuesta\x12K\n\x16ObtenerClientesPorArea\x12\x13.suscripciones.Area\x1a\x1c.suscripciones.ListaClientes\x12J\n\x15ObtenerNoticiasDeArea\x12\x13.suscripciones.Area\x1a\x1c.suscripciones.ListaNoticiasb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'suscripciones_noticias_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTEAREA']._serialized_start=47
  _globals['_CLIENTEAREA']._serialized_end=112
  _globals['_RESPUESTA']._serialized_start=114
  _globals['_RESPUESTA']._serialized_end=157
  _globals['_AREA']._serialized_start=159
  _globals['_AREA']._serialized_end=181
  _globals['_LISTACLIENTES']._serialized_start=183
  _globals['_LISTACLIENTES']._serialized_end=216
  _globals['_NOTICIA']._serialized_start=218
  _globals['_NOTICIA']._serialized_end=277
  _globals['_LISTANOTICIAS']._serialized_start=279
  _globals['_LISTANOTICIAS']._serialized_end=336
  _globals['_SUSCRIPCIONESNOTICIAS']._serialized_start=339
  _globals['_SUSCRIPCIONESNOTICIAS']._serialized_end=665
# @@protoc_insertion_point(module_scope)
